import type { ThemePresetValues } from "@editx/image-editor";

export const catppuccinLight: ThemePresetValues = {
  background: "#eff1f5",
  foreground: "#4c4f69",
  card: "#ffffff",
  "card-foreground": "#4c4f69",
  popover: "#ccd0da",
  "popover-foreground": "#4c4f69",
  primary: "#8839ef",
  "primary-foreground": "#ffffff",
  secondary: "#ccd0da",
  "secondary-foreground": "#4c4f69",
  muted: "#dce0e8",
  "muted-foreground": "#6c6f85",
  accent: "#04a5e5",
  "accent-foreground": "#ffffff",
  destructive: "#d20f39",
  "destructive-foreground": "#ffffff",
  border: "#bcc0cc",
  input: "#ccd0da",
  ring: "#8839ef",
  sidebar: "#e6e9ef",
  "sidebar-foreground": "#4c4f69",
  "sidebar-primary": "#8839ef",
  "sidebar-primary-foreground": "#ffffff",
  "sidebar-accent": "#04a5e5",
  "sidebar-accent-foreground": "#ffffff",
  "sidebar-border": "#bcc0cc",
  "sidebar-ring": "#8839ef",
};

export const catppuccinDark: ThemePresetValues = {
  background: "#181825",
  foreground: "#cdd6f4",
  card: "#1e1e2e",
  "card-foreground": "#cdd6f4",
  popover: "#45475a",
  "popover-foreground": "#cdd6f4",
  primary: "#cba6f7",
  "primary-foreground": "#1e1e2e",
  secondary: "#585b70",
  "secondary-foreground": "#cdd6f4",
  muted: "#292c3c",
  "muted-foreground": "#a6adc8",
  accent: "#89dceb",
  "accent-foreground": "#1e1e2e",
  destructive: "#f38ba8",
  "destructive-foreground": "#1e1e2e",
  border: "#313244",
  input: "#313244",
  ring: "#cba6f7",
  sidebar: "#11111b",
  "sidebar-foreground": "#cdd6f4",
  "sidebar-primary": "#cba6f7",
  "sidebar-primary-foreground": "#1e1e2e",
  "sidebar-accent": "#89dceb",
  "sidebar-accent-foreground": "#1e1e2e",
  "sidebar-border": "#45475a",
  "sidebar-ring": "#cba6f7",
};
