import type { ThemePresetValues } from "@editx/image-editor";

export const cosmicNightLight: ThemePresetValues = {
  background: "#f5f5ff",
  foreground: "#2a2a4a",
  card: "#ffffff",
  "card-foreground": "#2a2a4a",
  popover: "#ffffff",
  "popover-foreground": "#2a2a4a",
  primary: "#6e56cf",
  "primary-foreground": "#ffffff",
  secondary: "#e4dfff",
  "secondary-foreground": "#4a4080",
  muted: "#f0f0fa",
  "muted-foreground": "#6c6c8a",
  accent: "#d8e6ff",
  "accent-foreground": "#2a2a4a",
  destructive: "#ff5470",
  "destructive-foreground": "#ffffff",
  border: "#e0e0f0",
  input: "#e0e0f0",
  ring: "#6e56cf",
  sidebar: "#f0f0fa",
  "sidebar-foreground": "#2a2a4a",
  "sidebar-primary": "#6e56cf",
  "sidebar-primary-foreground": "#ffffff",
  "sidebar-accent": "#d8e6ff",
  "sidebar-accent-foreground": "#2a2a4a",
  "sidebar-border": "#e0e0f0",
  "sidebar-ring": "#6e56cf",
};

export const cosmicNightDark: ThemePresetValues = {
  background: "#0f0f1a",
  foreground: "#e2e2f5",
  card: "#1a1a2e",
  "card-foreground": "#e2e2f5",
  popover: "#1a1a2e",
  "popover-foreground": "#e2e2f5",
  primary: "#a48fff",
  "primary-foreground": "#0f0f1a",
  secondary: "#2d2b55",
  "secondary-foreground": "#c4c2ff",
  muted: "#222244",
  "muted-foreground": "#a0a0c0",
  accent: "#303060",
  "accent-foreground": "#e2e2f5",
  destructive: "#ff5470",
  "destructive-foreground": "#ffffff",
  border: "#303052",
  input: "#303052",
  ring: "#a48fff",
  sidebar: "#1a1a2e",
  "sidebar-foreground": "#e2e2f5",
  "sidebar-primary": "#a48fff",
  "sidebar-primary-foreground": "#0f0f1a",
  "sidebar-accent": "#303060",
  "sidebar-accent-foreground": "#e2e2f5",
  "sidebar-border": "#303052",
  "sidebar-ring": "#a48fff",
};
