import type { ThemePresetValues } from "@editx/image-editor";

export const cyberpunkLight: ThemePresetValues = {
  background: "#f8f9fa",
  foreground: "#0c0c1d",
  card: "#ffffff",
  "card-foreground": "#0c0c1d",
  popover: "#ffffff",
  "popover-foreground": "#0c0c1d",
  primary: "#ff00c8",
  "primary-foreground": "#ffffff",
  secondary: "#f0f0ff",
  "secondary-foreground": "#0c0c1d",
  muted: "#f0f0ff",
  "muted-foreground": "#0c0c1d",
  accent: "#00ffcc",
  "accent-foreground": "#0c0c1d",
  destructive: "#ff3d00",
  "destructive-foreground": "#ffffff",
  border: "#dfe6e9",
  input: "#dfe6e9",
  ring: "#ff00c8",
  sidebar: "#f0f0ff",
  "sidebar-foreground": "#0c0c1d",
  "sidebar-primary": "#ff00c8",
  "sidebar-primary-foreground": "#ffffff",
  "sidebar-accent": "#00ffcc",
  "sidebar-accent-foreground": "#0c0c1d",
  "sidebar-border": "#dfe6e9",
  "sidebar-ring": "#ff00c8",
};

export const cyberpunkDark: ThemePresetValues = {
  background: "#0c0c1d",
  foreground: "#eceff4",
  card: "#1e1e3f",
  "card-foreground": "#eceff4",
  popover: "#1e1e3f",
  "popover-foreground": "#eceff4",
  primary: "#ff00c8",
  "primary-foreground": "#ffffff",
  secondary: "#1e1e3f",
  "secondary-foreground": "#eceff4",
  muted: "#151530",
  "muted-foreground": "#8085a6",
  accent: "#00ffcc",
  "accent-foreground": "#0c0c1d",
  destructive: "#ff3d00",
  "destructive-foreground": "#ffffff",
  border: "#2e2e5e",
  input: "#2e2e5e",
  ring: "#ff00c8",
  sidebar: "#0c0c1d",
  "sidebar-foreground": "#eceff4",
  "sidebar-primary": "#ff00c8",
  "sidebar-primary-foreground": "#ffffff",
  "sidebar-accent": "#00ffcc",
  "sidebar-accent-foreground": "#0c0c1d",
  "sidebar-border": "#2e2e5e",
  "sidebar-ring": "#ff00c8",
};
