import type { ThemePresetValues } from "@editx/image-editor";

export const pastelDreamsLight: ThemePresetValues = {
  background: "#fdf4ff",
  foreground: "#581c87",
  card: "#ffffff",
  "card-foreground": "#581c87",
  popover: "#ffffff",
  "popover-foreground": "#581c87",
  primary: "#c084fc",
  "primary-foreground": "#ffffff",
  secondary: "#fae8ff",
  "secondary-foreground": "#7e22ce",
  muted: "#faf5ff",
  "muted-foreground": "#a855f7",
  accent: "#f5d0fe",
  "accent-foreground": "#581c87",
  destructive: "#e11d48",
  "destructive-foreground": "#ffffff",
  border: "#f0abfc",
  input: "#f0abfc",
  ring: "#c084fc",
  sidebar: "#fae8ff",
  "sidebar-foreground": "#581c87",
  "sidebar-primary": "#c084fc",
  "sidebar-primary-foreground": "#ffffff",
  "sidebar-accent": "#f5d0fe",
  "sidebar-accent-foreground": "#581c87",
  "sidebar-border": "#f0abfc",
  "sidebar-ring": "#c084fc",
};

export const pastelDreamsDark: ThemePresetValues = {
  background: "#1a0a2e",
  foreground: "#e9d5ff",
  card: "#2e1065",
  "card-foreground": "#e9d5ff",
  popover: "#2e1065",
  "popover-foreground": "#e9d5ff",
  primary: "#a855f7",
  "primary-foreground": "#1a0a2e",
  secondary: "#3b0764",
  "secondary-foreground": "#c4b5fd",
  muted: "#2e1065",
  "muted-foreground": "#a78bfa",
  accent: "#3b0764",
  "accent-foreground": "#e9d5ff",
  destructive: "#f43f5e",
  "destructive-foreground": "#1a0a2e",
  border: "#581c87",
  input: "#581c87",
  ring: "#a855f7",
  sidebar: "#2e1065",
  "sidebar-foreground": "#e9d5ff",
  "sidebar-primary": "#a855f7",
  "sidebar-primary-foreground": "#1a0a2e",
  "sidebar-accent": "#3b0764",
  "sidebar-accent-foreground": "#e9d5ff",
  "sidebar-border": "#581c87",
  "sidebar-ring": "#a855f7",
};
