import type { ThemePresetValues } from "@editx/image-editor";

export const t3ChatLight: ThemePresetValues = {
  background: "#ffffff",
  foreground: "#0a0a0a",
  card: "#ffffff",
  "card-foreground": "#0a0a0a",
  popover: "#ffffff",
  "popover-foreground": "#0a0a0a",
  primary: "#6d28d9",
  "primary-foreground": "#ffffff",
  secondary: "#f3f4f6",
  "secondary-foreground": "#374151",
  muted: "#f3f4f6",
  "muted-foreground": "#6b7280",
  accent: "#ede9fe",
  "accent-foreground": "#6d28d9",
  destructive: "#ef4444",
  "destructive-foreground": "#ffffff",
  border: "#e5e7eb",
  input: "#e5e7eb",
  ring: "#6d28d9",
  sidebar: "#f9fafb",
  "sidebar-foreground": "#0a0a0a",
  "sidebar-primary": "#6d28d9",
  "sidebar-primary-foreground": "#ffffff",
  "sidebar-accent": "#ede9fe",
  "sidebar-accent-foreground": "#6d28d9",
  "sidebar-border": "#e5e7eb",
  "sidebar-ring": "#6d28d9",
};

export const t3ChatDark: ThemePresetValues = {
  background: "#09090b",
  foreground: "#fafafa",
  card: "#131316",
  "card-foreground": "#fafafa",
  popover: "#131316",
  "popover-foreground": "#fafafa",
  primary: "#8b5cf6",
  "primary-foreground": "#09090b",
  secondary: "#1e1e24",
  "secondary-foreground": "#a1a1aa",
  muted: "#1e1e24",
  "muted-foreground": "#71717a",
  accent: "#2e1065",
  "accent-foreground": "#c4b5fd",
  destructive: "#ef4444",
  "destructive-foreground": "#09090b",
  border: "#27272a",
  input: "#27272a",
  ring: "#8b5cf6",
  sidebar: "#131316",
  "sidebar-foreground": "#fafafa",
  "sidebar-primary": "#8b5cf6",
  "sidebar-primary-foreground": "#09090b",
  "sidebar-accent": "#2e1065",
  "sidebar-accent-foreground": "#c4b5fd",
  "sidebar-border": "#27272a",
  "sidebar-ring": "#8b5cf6",
};
