// Generated by pnpm generate:thumbnails. Do not edit manually.
export const BUILT_IN_PRESET_THUMBNAILS: Readonly<Record<string, string>> = {
  "shape:filled-block-arrow:v1-aab45354": new URL(
    "../../assets/preset-thumbnails/shape-filled-block-arrow-v1-aab45354.png",
    import.meta.url,
  ).href,
  "shape:filled-capsule:v1-e9f5572e": new URL(
    "../../assets/preset-thumbnails/shape-filled-capsule-v1-e9f5572e.png",
    import.meta.url,
  ).href,
  "shape:filled-circle:v1-2ab61684": new URL(
    "../../assets/preset-thumbnails/shape-filled-circle-v1-2ab61684.png",
    import.meta.url,
  ).href,
  "shape:filled-diamond:v1-3d64f03d": new URL(
    "../../assets/preset-thumbnails/shape-filled-diamond-v1-3d64f03d.png",
    import.meta.url,
  ).href,
  "shape:filled-heart:v1-22c90a84": new URL(
    "../../assets/preset-thumbnails/shape-filled-heart-v1-22c90a84.png",
    import.meta.url,
  ).href,
  "shape:filled-pentagon:v1-203757f9": new URL(
    "../../assets/preset-thumbnails/shape-filled-pentagon-v1-203757f9.png",
    import.meta.url,
  ).href,
  "shape:filled-plus:v1-c18b00c4": new URL(
    "../../assets/preset-thumbnails/shape-filled-plus-v1-c18b00c4.png",
    import.meta.url,
  ).href,
  "shape:filled-rect:v1-6833d19a": new URL(
    "../../assets/preset-thumbnails/shape-filled-rect-v1-6833d19a.png",
    import.meta.url,
  ).href,
  "shape:filled-right-triangle:v1-52efcd76": new URL(
    "../../assets/preset-thumbnails/shape-filled-right-triangle-v1-52efcd76.png",
    import.meta.url,
  ).href,
  "shape:filled-rounded-rect:v1-d721bf58": new URL(
    "../../assets/preset-thumbnails/shape-filled-rounded-rect-v1-d721bf58.png",
    import.meta.url,
  ).href,
  "shape:filled-star:v1-6feb4f9c": new URL(
    "../../assets/preset-thumbnails/shape-filled-star-v1-6feb4f9c.png",
    import.meta.url,
  ).href,
  "shape:filled-triangle:v1-27de202b": new URL(
    "../../assets/preset-thumbnails/shape-filled-triangle-v1-27de202b.png",
    import.meta.url,
  ).href,
  "shape:gradient-block-arrow:v1-d876ba51": new URL(
    "../../assets/preset-thumbnails/shape-gradient-block-arrow-v1-d876ba51.png",
    import.meta.url,
  ).href,
  "shape:gradient-capsule:v1-ab7740e3": new URL(
    "../../assets/preset-thumbnails/shape-gradient-capsule-v1-ab7740e3.png",
    import.meta.url,
  ).href,
  "shape:gradient-diamond:v1-671e8d26": new URL(
    "../../assets/preset-thumbnails/shape-gradient-diamond-v1-671e8d26.png",
    import.meta.url,
  ).href,
  "shape:gradient-heart:v1-26a6ca3f": new URL(
    "../../assets/preset-thumbnails/shape-gradient-heart-v1-26a6ca3f.png",
    import.meta.url,
  ).href,
  "shape:gradient-ocean:v1-8e9a7d6f": new URL(
    "../../assets/preset-thumbnails/shape-gradient-ocean-v1-8e9a7d6f.png",
    import.meta.url,
  ).href,
  "shape:gradient-pentagon:v1-a4a96b4e": new URL(
    "../../assets/preset-thumbnails/shape-gradient-pentagon-v1-a4a96b4e.png",
    import.meta.url,
  ).href,
  "shape:gradient-plus:v1-a6e921a7": new URL(
    "../../assets/preset-thumbnails/shape-gradient-plus-v1-a6e921a7.png",
    import.meta.url,
  ).href,
  "shape:gradient-right-triangle:v1-94604469": new URL(
    "../../assets/preset-thumbnails/shape-gradient-right-triangle-v1-94604469.png",
    import.meta.url,
  ).href,
  "shape:gradient-rounded-rect:v1-8c6536e9": new URL(
    "../../assets/preset-thumbnails/shape-gradient-rounded-rect-v1-8c6536e9.png",
    import.meta.url,
  ).href,
  "shape:gradient-star:v1-907a9635": new URL(
    "../../assets/preset-thumbnails/shape-gradient-star-v1-907a9635.png",
    import.meta.url,
  ).href,
  "shape:gradient-sunset:v1-5c2bed3f": new URL(
    "../../assets/preset-thumbnails/shape-gradient-sunset-v1-5c2bed3f.png",
    import.meta.url,
  ).href,
  "shape:gradient-triangle:v1-dd821090": new URL(
    "../../assets/preset-thumbnails/shape-gradient-triangle-v1-dd821090.png",
    import.meta.url,
  ).href,
  "shape:image-block-arrow:v1-2b897326": new URL(
    "../../assets/preset-thumbnails/shape-image-block-arrow-v1-2b897326.png",
    import.meta.url,
  ).href,
  "shape:image-capsule:v1-0bd74dec": new URL(
    "../../assets/preset-thumbnails/shape-image-capsule-v1-0bd74dec.png",
    import.meta.url,
  ).href,
  "shape:image-circle:v1-ab92735a": new URL(
    "../../assets/preset-thumbnails/shape-image-circle-v1-ab92735a.png",
    import.meta.url,
  ).href,
  "shape:image-diamond:v1-86e995ef": new URL(
    "../../assets/preset-thumbnails/shape-image-diamond-v1-86e995ef.png",
    import.meta.url,
  ).href,
  "shape:image-heart:v1-205cf3de": new URL(
    "../../assets/preset-thumbnails/shape-image-heart-v1-205cf3de.png",
    import.meta.url,
  ).href,
  "shape:image-pentagon:v1-6c7626ff": new URL(
    "../../assets/preset-thumbnails/shape-image-pentagon-v1-6c7626ff.png",
    import.meta.url,
  ).href,
  "shape:image-plus:v1-1118b46e": new URL(
    "../../assets/preset-thumbnails/shape-image-plus-v1-1118b46e.png",
    import.meta.url,
  ).href,
  "shape:image-rect:v1-433e9e38": new URL(
    "../../assets/preset-thumbnails/shape-image-rect-v1-433e9e38.png",
    import.meta.url,
  ).href,
  "shape:image-right-triangle:v1-9349b218": new URL(
    "../../assets/preset-thumbnails/shape-image-right-triangle-v1-9349b218.png",
    import.meta.url,
  ).href,
  "shape:image-rounded-rect:v1-6e4e544a": new URL(
    "../../assets/preset-thumbnails/shape-image-rounded-rect-v1-6e4e544a.png",
    import.meta.url,
  ).href,
  "shape:image-star:v1-a0c0c572": new URL(
    "../../assets/preset-thumbnails/shape-image-star-v1-a0c0c572.png",
    import.meta.url,
  ).href,
  "shape:image-triangle:v1-ea6c2e35": new URL(
    "../../assets/preset-thumbnails/shape-image-triangle-v1-ea6c2e35.png",
    import.meta.url,
  ).href,
  "shape:outline-block-arrow:v1-0624c55c": new URL(
    "../../assets/preset-thumbnails/shape-outline-block-arrow-v1-0624c55c.png",
    import.meta.url,
  ).href,
  "shape:outline-capsule:v1-38129cce": new URL(
    "../../assets/preset-thumbnails/shape-outline-capsule-v1-38129cce.png",
    import.meta.url,
  ).href,
  "shape:outline-circle:v1-225184e2": new URL(
    "../../assets/preset-thumbnails/shape-outline-circle-v1-225184e2.png",
    import.meta.url,
  ).href,
  "shape:outline-diamond:v1-1a45bcb5": new URL(
    "../../assets/preset-thumbnails/shape-outline-diamond-v1-1a45bcb5.png",
    import.meta.url,
  ).href,
  "shape:outline-heart:v1-90bc972e": new URL(
    "../../assets/preset-thumbnails/shape-outline-heart-v1-90bc972e.png",
    import.meta.url,
  ).href,
  "shape:outline-pentagon:v1-f71bd539": new URL(
    "../../assets/preset-thumbnails/shape-outline-pentagon-v1-f71bd539.png",
    import.meta.url,
  ).href,
  "shape:outline-plus:v1-23e370d6": new URL(
    "../../assets/preset-thumbnails/shape-outline-plus-v1-23e370d6.png",
    import.meta.url,
  ).href,
  "shape:outline-rect:v1-e0f95c1a": new URL(
    "../../assets/preset-thumbnails/shape-outline-rect-v1-e0f95c1a.png",
    import.meta.url,
  ).href,
  "shape:outline-right-triangle:v1-cc22dbcc": new URL(
    "../../assets/preset-thumbnails/shape-outline-right-triangle-v1-cc22dbcc.png",
    import.meta.url,
  ).href,
  "shape:outline-rounded-rect:v1-c6700834": new URL(
    "../../assets/preset-thumbnails/shape-outline-rounded-rect-v1-c6700834.png",
    import.meta.url,
  ).href,
  "shape:outline-star:v1-3e698f94": new URL(
    "../../assets/preset-thumbnails/shape-outline-star-v1-3e698f94.png",
    import.meta.url,
  ).href,
  "shape:outline-triangle:v1-58917fc3": new URL(
    "../../assets/preset-thumbnails/shape-outline-triangle-v1-58917fc3.png",
    import.meta.url,
  ).href,
  "shape:path-arch:v1-3b9a1e38": new URL(
    "../../assets/preset-thumbnails/shape-path-arch-v1-3b9a1e38.png",
    import.meta.url,
  ).href,
  "shape:path-blob:v1-57a33739": new URL(
    "../../assets/preset-thumbnails/shape-path-blob-v1-57a33739.png",
    import.meta.url,
  ).href,
  "shape:path-burst:v1-3f1fbb40": new URL(
    "../../assets/preset-thumbnails/shape-path-burst-v1-3f1fbb40.png",
    import.meta.url,
  ).href,
  "shape:path-chat:v1-47356b44": new URL(
    "../../assets/preset-thumbnails/shape-path-chat-v1-47356b44.png",
    import.meta.url,
  ).href,
  "shape:path-clover:v1-6df9c8a8": new URL(
    "../../assets/preset-thumbnails/shape-path-clover-v1-6df9c8a8.png",
    import.meta.url,
  ).href,
  "shape:path-crescent:v1-e71d6e66": new URL(
    "../../assets/preset-thumbnails/shape-path-crescent-v1-e71d6e66.png",
    import.meta.url,
  ).href,
  "shape:path-heart:v1-e2cedd69": new URL(
    "../../assets/preset-thumbnails/shape-path-heart-v1-e2cedd69.png",
    import.meta.url,
  ).href,
  "shape:path-semicircle:v1-009992a3": new URL(
    "../../assets/preset-thumbnails/shape-path-semicircle-v1-009992a3.png",
    import.meta.url,
  ).href,
  "shape:path-sparkle:v1-05c93aed": new URL(
    "../../assets/preset-thumbnails/shape-path-sparkle-v1-05c93aed.png",
    import.meta.url,
  ).href,
  "shape:path-sunburst:v1-5bafedb2": new URL(
    "../../assets/preset-thumbnails/shape-path-sunburst-v1-5bafedb2.png",
    import.meta.url,
  ).href,
  "shape:path-teardrop:v1-93caa7b5": new URL(
    "../../assets/preset-thumbnails/shape-path-teardrop-v1-93caa7b5.png",
    import.meta.url,
  ).href,
  "shape:path-wave:v1-05cec571": new URL(
    "../../assets/preset-thumbnails/shape-path-wave-v1-05cec571.png",
    import.meta.url,
  ).href,
  "text:arc-down:v1-252565df": new URL(
    "../../assets/preset-thumbnails/text-arc-down-v1-252565df.png",
    import.meta.url,
  ).href,
  "text:arc-up:v1-55573e6f": new URL(
    "../../assets/preset-thumbnails/text-arc-up-v1-55573e6f.png",
    import.meta.url,
  ).href,
  "text:body:v1-d8be880a": new URL(
    "../../assets/preset-thumbnails/text-body-v1-d8be880a.png",
    import.meta.url,
  ).href,
  "text:bold-caps:v1-026bbf4c": new URL(
    "../../assets/preset-thumbnails/text-bold-caps-v1-026bbf4c.png",
    import.meta.url,
  ).href,
  "text:breaking-news:v1-8e23a9ad": new URL(
    "../../assets/preset-thumbnails/text-breaking-news-v1-8e23a9ad.png",
    import.meta.url,
  ).href,
  "text:chapter-opener:v1-d2afdca1": new URL(
    "../../assets/preset-thumbnails/text-chapter-opener-v1-d2afdca1.png",
    import.meta.url,
  ).href,
  "text:chapter:v1-b025c99f": new URL(
    "../../assets/preset-thumbnails/text-chapter-v1-b025c99f.png",
    import.meta.url,
  ).href,
  "text:cinematic:v1-10628226": new URL(
    "../../assets/preset-thumbnails/text-cinematic-v1-10628226.png",
    import.meta.url,
  ).href,
  "text:color-pop:v1-3b60d502": new URL(
    "../../assets/preset-thumbnails/text-color-pop-v1-3b60d502.png",
    import.meta.url,
  ).href,
  "text:colorful:v1-0d8d2346": new URL(
    "../../assets/preset-thumbnails/text-colorful-v1-0d8d2346.png",
    import.meta.url,
  ).href,
  "text:countdown:v1-1e010f0c": new URL(
    "../../assets/preset-thumbnails/text-countdown-v1-1e010f0c.png",
    import.meta.url,
  ).href,
  "text:editorial-switch:v1-0122d855": new URL(
    "../../assets/preset-thumbnails/text-editorial-switch-v1-0122d855.png",
    import.meta.url,
  ).href,
  "text:elegant:v1-04762c94": new URL(
    "../../assets/preset-thumbnails/text-elegant-v1-04762c94.png",
    import.meta.url,
  ).href,
  "text:event-details:v1-49d4571a": new URL(
    "../../assets/preset-thumbnails/text-event-details-v1-49d4571a.png",
    import.meta.url,
  ).href,
  "text:glitch-cut:v1-39469be7": new URL(
    "../../assets/preset-thumbnails/text-glitch-cut-v1-39469be7.png",
    import.meta.url,
  ).href,
  "text:heading-subtitle:v1-9abfd827": new URL(
    "../../assets/preset-thumbnails/text-heading-subtitle-v1-9abfd827.png",
    import.meta.url,
  ).href,
  "text:heading:v1-1b25f994": new URL(
    "../../assets/preset-thumbnails/text-heading-v1-1b25f994.png",
    import.meta.url,
  ).href,
  "text:highlight:v1-8a901fe8": new URL(
    "../../assets/preset-thumbnails/text-highlight-v1-8a901fe8.png",
    import.meta.url,
  ).href,
  "text:ink-frame:v1-6e0a7473": new URL(
    "../../assets/preset-thumbnails/text-ink-frame-v1-6e0a7473.png",
    import.meta.url,
  ).href,
  "text:issue-cover:v1-35aa3fc4": new URL(
    "../../assets/preset-thumbnails/text-issue-cover-v1-35aa3fc4.png",
    import.meta.url,
  ).href,
  "text:modern:v1-dc814ab4": new URL(
    "../../assets/preset-thumbnails/text-modern-v1-dc814ab4.png",
    import.meta.url,
  ).href,
  "text:mono-loading:v1-7b5d3d98": new URL(
    "../../assets/preset-thumbnails/text-mono-loading-v1-7b5d3d98.png",
    import.meta.url,
  ).href,
  "text:monogram-seal:v1-4d36e762": new URL(
    "../../assets/preset-thumbnails/text-monogram-seal-v1-4d36e762.png",
    import.meta.url,
  ).href,
  "text:name-role:v1-b6393213": new URL(
    "../../assets/preset-thumbnails/text-name-role-v1-b6393213.png",
    import.meta.url,
  ).href,
  "text:neon:v1-c3de108c": new URL(
    "../../assets/preset-thumbnails/text-neon-v1-c3de108c.png",
    import.meta.url,
  ).href,
  "text:new-arrival:v1-873cfab0": new URL(
    "../../assets/preset-thumbnails/text-new-arrival-v1-873cfab0.png",
    import.meta.url,
  ).href,
  "text:offset-card:v1-6cd50865": new URL(
    "../../assets/preset-thumbnails/text-offset-card-v1-6cd50865.png",
    import.meta.url,
  ).href,
  "text:outline:v1-e822dbd6": new URL(
    "../../assets/preset-thumbnails/text-outline-v1-e822dbd6.png",
    import.meta.url,
  ).href,
  "text:phantom:v1-35ed0a35": new URL(
    "../../assets/preset-thumbnails/text-phantom-v1-35ed0a35.png",
    import.meta.url,
  ).href,
  "text:photo-caption:v1-0b75aac9": new URL(
    "../../assets/preset-thumbnails/text-photo-caption-v1-0b75aac9.png",
    import.meta.url,
  ).href,
  "text:postcard:v1-6e82ca20": new URL(
    "../../assets/preset-thumbnails/text-postcard-v1-6e82ca20.png",
    import.meta.url,
  ).href,
  "text:price-stack:v1-8523b657": new URL(
    "../../assets/preset-thumbnails/text-price-stack-v1-8523b657.png",
    import.meta.url,
  ).href,
  "text:promo-code:v1-fefe6aaa": new URL(
    "../../assets/preset-thumbnails/text-promo-code-v1-fefe6aaa.png",
    import.meta.url,
  ).href,
  "text:pull-quote:v1-db4e9449": new URL(
    "../../assets/preset-thumbnails/text-pull-quote-v1-db4e9449.png",
    import.meta.url,
  ).href,
  "text:quote:v1-821ca04b": new URL(
    "../../assets/preset-thumbnails/text-quote-v1-821ca04b.png",
    import.meta.url,
  ).href,
  "text:rsvp-card:v1-aaa13e14": new URL(
    "../../assets/preset-thumbnails/text-rsvp-card-v1-aaa13e14.png",
    import.meta.url,
  ).href,
  "text:sale-badge:v1-2ce1b463": new URL(
    "../../assets/preset-thumbnails/text-sale-badge-v1-2ce1b463.png",
    import.meta.url,
  ).href,
  "text:shadow:v1-8c0dab55": new URL(
    "../../assets/preset-thumbnails/text-shadow-v1-8c0dab55.png",
    import.meta.url,
  ).href,
  "text:shipping-banner:v1-e104dcc4": new URL(
    "../../assets/preset-thumbnails/text-shipping-banner-v1-e104dcc4.png",
    import.meta.url,
  ).href,
  "text:so-sunny:v1-170cf1b3": new URL(
    "../../assets/preset-thumbnails/text-so-sunny-v1-170cf1b3.png",
    import.meta.url,
  ).href,
  "text:social-proof:v1-7dab8b4e": new URL(
    "../../assets/preset-thumbnails/text-social-proof-v1-7dab8b4e.png",
    import.meta.url,
  ).href,
  "text:soft-club:v1-5794d902": new URL(
    "../../assets/preset-thumbnails/text-soft-club-v1-5794d902.png",
    import.meta.url,
  ).href,
  "text:soft-shadow:v1-f4a22548": new URL(
    "../../assets/preset-thumbnails/text-soft-shadow-v1-f4a22548.png",
    import.meta.url,
  ).href,
  "text:sticker:v1-e55fa1fb": new URL(
    "../../assets/preset-thumbnails/text-sticker-v1-e55fa1fb.png",
    import.meta.url,
  ).href,
  "text:strawberry:v1-14ab47f3": new URL(
    "../../assets/preset-thumbnails/text-strawberry-v1-14ab47f3.png",
    import.meta.url,
  ).href,
  "text:subheading:v1-e9e22973": new URL(
    "../../assets/preset-thumbnails/text-subheading-v1-e9e22973.png",
    import.meta.url,
  ).href,
  "text:sunset:v1-de1e2ea4": new URL(
    "../../assets/preset-thumbnails/text-sunset-v1-de1e2ea4.png",
    import.meta.url,
  ).href,
  "text:team:v1-b20313be": new URL(
    "../../assets/preset-thumbnails/text-team-v1-b20313be.png",
    import.meta.url,
  ).href,
  "text:text-box:v1-eda89632": new URL(
    "../../assets/preset-thumbnails/text-text-box-v1-eda89632.png",
    import.meta.url,
  ).href,
  "text:thanks-plus:v1-bd506583": new URL(
    "../../assets/preset-thumbnails/text-thanks-plus-v1-bd506583.png",
    import.meta.url,
  ).href,
  "text:title-tag:v1-ff472b84": new URL(
    "../../assets/preset-thumbnails/text-title-tag-v1-ff472b84.png",
    import.meta.url,
  ).href,
  "text:title:v1-ca4a2f6c": new URL(
    "../../assets/preset-thumbnails/text-title-v1-ca4a2f6c.png",
    import.meta.url,
  ).href,
};
