// Generated by pnpm generate:thumbnails. Do not edit manually.
export const BUILT_IN_PRESET_THUMBNAILS: Readonly<Record<string, string>> = {
  "shape:filled-block-arrow:v1-1fef0fa6": new URL(
    "../../assets/preset-thumbnails/shape-filled-block-arrow-v1-1fef0fa6.png",
    import.meta.url,
  ).href,
  "shape:filled-capsule:v1-6f99466c": new URL(
    "../../assets/preset-thumbnails/shape-filled-capsule-v1-6f99466c.png",
    import.meta.url,
  ).href,
  "shape:filled-circle:v1-1e5544da": new URL(
    "../../assets/preset-thumbnails/shape-filled-circle-v1-1e5544da.png",
    import.meta.url,
  ).href,
  "shape:filled-diamond:v1-a8aa8f6f": new URL(
    "../../assets/preset-thumbnails/shape-filled-diamond-v1-a8aa8f6f.png",
    import.meta.url,
  ).href,
  "shape:filled-heart:v1-c4d2255e": new URL(
    "../../assets/preset-thumbnails/shape-filled-heart-v1-c4d2255e.png",
    import.meta.url,
  ).href,
  "shape:filled-pentagon:v1-e8b5447f": new URL(
    "../../assets/preset-thumbnails/shape-filled-pentagon-v1-e8b5447f.png",
    import.meta.url,
  ).href,
  "shape:filled-plus:v1-2b7725ee": new URL(
    "../../assets/preset-thumbnails/shape-filled-plus-v1-2b7725ee.png",
    import.meta.url,
  ).href,
  "shape:filled-rect:v1-f392a2b8": new URL(
    "../../assets/preset-thumbnails/shape-filled-rect-v1-f392a2b8.png",
    import.meta.url,
  ).href,
  "shape:filled-right-triangle:v1-1427d798": new URL(
    "../../assets/preset-thumbnails/shape-filled-right-triangle-v1-1427d798.png",
    import.meta.url,
  ).href,
  "shape:filled-rounded-rect:v1-d2104cca": new URL(
    "../../assets/preset-thumbnails/shape-filled-rounded-rect-v1-d2104cca.png",
    import.meta.url,
  ).href,
  "shape:filled-star:v1-397109f2": new URL(
    "../../assets/preset-thumbnails/shape-filled-star-v1-397109f2.png",
    import.meta.url,
  ).href,
  "shape:filled-triangle:v1-66ab4bb5": new URL(
    "../../assets/preset-thumbnails/shape-filled-triangle-v1-66ab4bb5.png",
    import.meta.url,
  ).href,
  "shape:gradient-block-arrow:v1-157147ab": new URL(
    "../../assets/preset-thumbnails/shape-gradient-block-arrow-v1-157147ab.png",
    import.meta.url,
  ).href,
  "shape:gradient-capsule:v1-cb962321": new URL(
    "../../assets/preset-thumbnails/shape-gradient-capsule-v1-cb962321.png",
    import.meta.url,
  ).href,
  "shape:gradient-diamond:v1-6363e598": new URL(
    "../../assets/preset-thumbnails/shape-gradient-diamond-v1-6363e598.png",
    import.meta.url,
  ).href,
  "shape:gradient-heart:v1-1552d6a1": new URL(
    "../../assets/preset-thumbnails/shape-gradient-heart-v1-1552d6a1.png",
    import.meta.url,
  ).href,
  "shape:gradient-ocean:v1-f8700535": new URL(
    "../../assets/preset-thumbnails/shape-gradient-ocean-v1-f8700535.png",
    import.meta.url,
  ).href,
  "shape:gradient-pentagon:v1-d2953d1c": new URL(
    "../../assets/preset-thumbnails/shape-gradient-pentagon-v1-d2953d1c.png",
    import.meta.url,
  ).href,
  "shape:gradient-plus:v1-60f02609": new URL(
    "../../assets/preset-thumbnails/shape-gradient-plus-v1-60f02609.png",
    import.meta.url,
  ).href,
  "shape:gradient-right-triangle:v1-715de71b": new URL(
    "../../assets/preset-thumbnails/shape-gradient-right-triangle-v1-715de71b.png",
    import.meta.url,
  ).href,
  "shape:gradient-rounded-rect:v1-8611c1e3": new URL(
    "../../assets/preset-thumbnails/shape-gradient-rounded-rect-v1-8611c1e3.png",
    import.meta.url,
  ).href,
  "shape:gradient-star:v1-df752663": new URL(
    "../../assets/preset-thumbnails/shape-gradient-star-v1-df752663.png",
    import.meta.url,
  ).href,
  "shape:gradient-sunset:v1-3869b56d": new URL(
    "../../assets/preset-thumbnails/shape-gradient-sunset-v1-3869b56d.png",
    import.meta.url,
  ).href,
  "shape:gradient-triangle:v1-5c753ad2": new URL(
    "../../assets/preset-thumbnails/shape-gradient-triangle-v1-5c753ad2.png",
    import.meta.url,
  ).href,
  "shape:image-block-arrow:v1-cf41816b": new URL(
    "../../assets/preset-thumbnails/shape-image-block-arrow-v1-cf41816b.png",
    import.meta.url,
  ).href,
  "shape:image-capsule:v1-698beee1": new URL(
    "../../assets/preset-thumbnails/shape-image-capsule-v1-698beee1.png",
    import.meta.url,
  ).href,
  "shape:image-circle:v1-8d2f4af5": new URL(
    "../../assets/preset-thumbnails/shape-image-circle-v1-8d2f4af5.png",
    import.meta.url,
  ).href,
  "shape:image-diamond:v1-fdc6e9d8": new URL(
    "../../assets/preset-thumbnails/shape-image-diamond-v1-fdc6e9d8.png",
    import.meta.url,
  ).href,
  "shape:image-heart:v1-7751ed61": new URL(
    "../../assets/preset-thumbnails/shape-image-heart-v1-7751ed61.png",
    import.meta.url,
  ).href,
  "shape:image-pentagon:v1-d846305c": new URL(
    "../../assets/preset-thumbnails/shape-image-pentagon-v1-d846305c.png",
    import.meta.url,
  ).href,
  "shape:image-plus:v1-a59840c9": new URL(
    "../../assets/preset-thumbnails/shape-image-plus-v1-a59840c9.png",
    import.meta.url,
  ).href,
  "shape:image-rect:v1-71ccc72d": new URL(
    "../../assets/preset-thumbnails/shape-image-rect-v1-71ccc72d.png",
    import.meta.url,
  ).href,
  "shape:image-right-triangle:v1-04e223db": new URL(
    "../../assets/preset-thumbnails/shape-image-right-triangle-v1-04e223db.png",
    import.meta.url,
  ).href,
  "shape:image-rounded-rect:v1-4735e7a3": new URL(
    "../../assets/preset-thumbnails/shape-image-rounded-rect-v1-4735e7a3.png",
    import.meta.url,
  ).href,
  "shape:image-star:v1-68ef2ba3": new URL(
    "../../assets/preset-thumbnails/shape-image-star-v1-68ef2ba3.png",
    import.meta.url,
  ).href,
  "shape:image-triangle:v1-c3536912": new URL(
    "../../assets/preset-thumbnails/shape-image-triangle-v1-c3536912.png",
    import.meta.url,
  ).href,
  "shape:outline-block-arrow:v1-b5f71696": new URL(
    "../../assets/preset-thumbnails/shape-outline-block-arrow-v1-b5f71696.png",
    import.meta.url,
  ).href,
  "shape:outline-capsule:v1-b94106dc": new URL(
    "../../assets/preset-thumbnails/shape-outline-capsule-v1-b94106dc.png",
    import.meta.url,
  ).href,
  "shape:outline-circle:v1-12cc9ba8": new URL(
    "../../assets/preset-thumbnails/shape-outline-circle-v1-12cc9ba8.png",
    import.meta.url,
  ).href,
  "shape:outline-diamond:v1-c95edccf": new URL(
    "../../assets/preset-thumbnails/shape-outline-diamond-v1-c95edccf.png",
    import.meta.url,
  ).href,
  "shape:outline-heart:v1-f208b018": new URL(
    "../../assets/preset-thumbnails/shape-outline-heart-v1-f208b018.png",
    import.meta.url,
  ).href,
  "shape:outline-pentagon:v1-1877eaf7": new URL(
    "../../assets/preset-thumbnails/shape-outline-pentagon-v1-1877eaf7.png",
    import.meta.url,
  ).href,
  "shape:outline-plus:v1-77b08710": new URL(
    "../../assets/preset-thumbnails/shape-outline-plus-v1-77b08710.png",
    import.meta.url,
  ).href,
  "shape:outline-rect:v1-1f30deb8": new URL(
    "../../assets/preset-thumbnails/shape-outline-rect-v1-1f30deb8.png",
    import.meta.url,
  ).href,
  "shape:outline-right-triangle:v1-5cd45ffe": new URL(
    "../../assets/preset-thumbnails/shape-outline-right-triangle-v1-5cd45ffe.png",
    import.meta.url,
  ).href,
  "shape:outline-rounded-rect:v1-b6f2153e": new URL(
    "../../assets/preset-thumbnails/shape-outline-rounded-rect-v1-b6f2153e.png",
    import.meta.url,
  ).href,
  "shape:outline-star:v1-7b1bc66a": new URL(
    "../../assets/preset-thumbnails/shape-outline-star-v1-7b1bc66a.png",
    import.meta.url,
  ).href,
  "shape:outline-triangle:v1-44ae98b5": new URL(
    "../../assets/preset-thumbnails/shape-outline-triangle-v1-44ae98b5.png",
    import.meta.url,
  ).href,
  "shape:path-arch:v1-e6b3c2ba": new URL(
    "../../assets/preset-thumbnails/shape-path-arch-v1-e6b3c2ba.png",
    import.meta.url,
  ).href,
  "shape:path-blob:v1-23b1b9db": new URL(
    "../../assets/preset-thumbnails/shape-path-blob-v1-23b1b9db.png",
    import.meta.url,
  ).href,
  "shape:path-burst:v1-eb2b1b62": new URL(
    "../../assets/preset-thumbnails/shape-path-burst-v1-eb2b1b62.png",
    import.meta.url,
  ).href,
  "shape:path-chat:v1-a4d929ca": new URL(
    "../../assets/preset-thumbnails/shape-path-chat-v1-a4d929ca.png",
    import.meta.url,
  ).href,
  "shape:path-clover:v1-ce8eb8fa": new URL(
    "../../assets/preset-thumbnails/shape-path-clover-v1-ce8eb8fa.png",
    import.meta.url,
  ).href,
  "shape:path-crescent:v1-a7121040": new URL(
    "../../assets/preset-thumbnails/shape-path-crescent-v1-a7121040.png",
    import.meta.url,
  ).href,
  "shape:path-heart:v1-ec8660cf": new URL(
    "../../assets/preset-thumbnails/shape-path-heart-v1-ec8660cf.png",
    import.meta.url,
  ).href,
  "shape:path-semicircle:v1-672ad95d": new URL(
    "../../assets/preset-thumbnails/shape-path-semicircle-v1-672ad95d.png",
    import.meta.url,
  ).href,
  "shape:path-sparkle:v1-f998756b": new URL(
    "../../assets/preset-thumbnails/shape-path-sparkle-v1-f998756b.png",
    import.meta.url,
  ).href,
  "shape:path-sunburst:v1-4620bd5c": new URL(
    "../../assets/preset-thumbnails/shape-path-sunburst-v1-4620bd5c.png",
    import.meta.url,
  ).href,
  "shape:path-teardrop:v1-d20029c7": new URL(
    "../../assets/preset-thumbnails/shape-path-teardrop-v1-d20029c7.png",
    import.meta.url,
  ).href,
  "shape:path-wave:v1-16920097": new URL(
    "../../assets/preset-thumbnails/shape-path-wave-v1-16920097.png",
    import.meta.url,
  ).href,
  "text:arc-down:v1-252565df": new URL(
    "../../assets/preset-thumbnails/text-arc-down-v1-252565df.png",
    import.meta.url,
  ).href,
  "text:arc-up:v1-55573e6f": new URL(
    "../../assets/preset-thumbnails/text-arc-up-v1-55573e6f.png",
    import.meta.url,
  ).href,
  "text:body:v1-d8be880a": new URL(
    "../../assets/preset-thumbnails/text-body-v1-d8be880a.png",
    import.meta.url,
  ).href,
  "text:bold-caps:v1-026bbf4c": new URL(
    "../../assets/preset-thumbnails/text-bold-caps-v1-026bbf4c.png",
    import.meta.url,
  ).href,
  "text:breaking-news:v1-8e23a9ad": new URL(
    "../../assets/preset-thumbnails/text-breaking-news-v1-8e23a9ad.png",
    import.meta.url,
  ).href,
  "text:chapter-opener:v1-d2afdca1": new URL(
    "../../assets/preset-thumbnails/text-chapter-opener-v1-d2afdca1.png",
    import.meta.url,
  ).href,
  "text:chapter:v1-b025c99f": new URL(
    "../../assets/preset-thumbnails/text-chapter-v1-b025c99f.png",
    import.meta.url,
  ).href,
  "text:cinematic:v1-10628226": new URL(
    "../../assets/preset-thumbnails/text-cinematic-v1-10628226.png",
    import.meta.url,
  ).href,
  "text:color-pop:v1-3b60d502": new URL(
    "../../assets/preset-thumbnails/text-color-pop-v1-3b60d502.png",
    import.meta.url,
  ).href,
  "text:colorful:v1-0d8d2346": new URL(
    "../../assets/preset-thumbnails/text-colorful-v1-0d8d2346.png",
    import.meta.url,
  ).href,
  "text:countdown:v1-1e010f0c": new URL(
    "../../assets/preset-thumbnails/text-countdown-v1-1e010f0c.png",
    import.meta.url,
  ).href,
  "text:editorial-switch:v1-0122d855": new URL(
    "../../assets/preset-thumbnails/text-editorial-switch-v1-0122d855.png",
    import.meta.url,
  ).href,
  "text:elegant:v1-04762c94": new URL(
    "../../assets/preset-thumbnails/text-elegant-v1-04762c94.png",
    import.meta.url,
  ).href,
  "text:event-details:v1-49d4571a": new URL(
    "../../assets/preset-thumbnails/text-event-details-v1-49d4571a.png",
    import.meta.url,
  ).href,
  "text:glitch-cut:v1-39469be7": new URL(
    "../../assets/preset-thumbnails/text-glitch-cut-v1-39469be7.png",
    import.meta.url,
  ).href,
  "text:heading-subtitle:v1-9abfd827": new URL(
    "../../assets/preset-thumbnails/text-heading-subtitle-v1-9abfd827.png",
    import.meta.url,
  ).href,
  "text:heading:v1-1b25f994": new URL(
    "../../assets/preset-thumbnails/text-heading-v1-1b25f994.png",
    import.meta.url,
  ).href,
  "text:highlight:v1-8a901fe8": new URL(
    "../../assets/preset-thumbnails/text-highlight-v1-8a901fe8.png",
    import.meta.url,
  ).href,
  "text:ink-frame:v1-6e0a7473": new URL(
    "../../assets/preset-thumbnails/text-ink-frame-v1-6e0a7473.png",
    import.meta.url,
  ).href,
  "text:issue-cover:v1-35aa3fc4": new URL(
    "../../assets/preset-thumbnails/text-issue-cover-v1-35aa3fc4.png",
    import.meta.url,
  ).href,
  "text:modern:v1-dc814ab4": new URL(
    "../../assets/preset-thumbnails/text-modern-v1-dc814ab4.png",
    import.meta.url,
  ).href,
  "text:mono-loading:v1-7b5d3d98": new URL(
    "../../assets/preset-thumbnails/text-mono-loading-v1-7b5d3d98.png",
    import.meta.url,
  ).href,
  "text:monogram-seal:v1-4d36e762": new URL(
    "../../assets/preset-thumbnails/text-monogram-seal-v1-4d36e762.png",
    import.meta.url,
  ).href,
  "text:name-role:v1-b6393213": new URL(
    "../../assets/preset-thumbnails/text-name-role-v1-b6393213.png",
    import.meta.url,
  ).href,
  "text:neon:v1-c3de108c": new URL(
    "../../assets/preset-thumbnails/text-neon-v1-c3de108c.png",
    import.meta.url,
  ).href,
  "text:new-arrival:v1-873cfab0": new URL(
    "../../assets/preset-thumbnails/text-new-arrival-v1-873cfab0.png",
    import.meta.url,
  ).href,
  "text:offset-card:v1-6cd50865": new URL(
    "../../assets/preset-thumbnails/text-offset-card-v1-6cd50865.png",
    import.meta.url,
  ).href,
  "text:outline:v1-e822dbd6": new URL(
    "../../assets/preset-thumbnails/text-outline-v1-e822dbd6.png",
    import.meta.url,
  ).href,
  "text:phantom:v1-35ed0a35": new URL(
    "../../assets/preset-thumbnails/text-phantom-v1-35ed0a35.png",
    import.meta.url,
  ).href,
  "text:photo-caption:v1-0b75aac9": new URL(
    "../../assets/preset-thumbnails/text-photo-caption-v1-0b75aac9.png",
    import.meta.url,
  ).href,
  "text:postcard:v1-6e82ca20": new URL(
    "../../assets/preset-thumbnails/text-postcard-v1-6e82ca20.png",
    import.meta.url,
  ).href,
  "text:price-stack:v1-8523b657": new URL(
    "../../assets/preset-thumbnails/text-price-stack-v1-8523b657.png",
    import.meta.url,
  ).href,
  "text:promo-code:v1-fefe6aaa": new URL(
    "../../assets/preset-thumbnails/text-promo-code-v1-fefe6aaa.png",
    import.meta.url,
  ).href,
  "text:pull-quote:v1-db4e9449": new URL(
    "../../assets/preset-thumbnails/text-pull-quote-v1-db4e9449.png",
    import.meta.url,
  ).href,
  "text:quote:v1-821ca04b": new URL(
    "../../assets/preset-thumbnails/text-quote-v1-821ca04b.png",
    import.meta.url,
  ).href,
  "text:rsvp-card:v1-aaa13e14": new URL(
    "../../assets/preset-thumbnails/text-rsvp-card-v1-aaa13e14.png",
    import.meta.url,
  ).href,
  "text:sale-badge:v1-2ce1b463": new URL(
    "../../assets/preset-thumbnails/text-sale-badge-v1-2ce1b463.png",
    import.meta.url,
  ).href,
  "text:shadow:v1-8c0dab55": new URL(
    "../../assets/preset-thumbnails/text-shadow-v1-8c0dab55.png",
    import.meta.url,
  ).href,
  "text:shipping-banner:v1-e104dcc4": new URL(
    "../../assets/preset-thumbnails/text-shipping-banner-v1-e104dcc4.png",
    import.meta.url,
  ).href,
  "text:so-sunny:v1-170cf1b3": new URL(
    "../../assets/preset-thumbnails/text-so-sunny-v1-170cf1b3.png",
    import.meta.url,
  ).href,
  "text:social-proof:v1-7dab8b4e": new URL(
    "../../assets/preset-thumbnails/text-social-proof-v1-7dab8b4e.png",
    import.meta.url,
  ).href,
  "text:soft-club:v1-5794d902": new URL(
    "../../assets/preset-thumbnails/text-soft-club-v1-5794d902.png",
    import.meta.url,
  ).href,
  "text:soft-shadow:v1-f4a22548": new URL(
    "../../assets/preset-thumbnails/text-soft-shadow-v1-f4a22548.png",
    import.meta.url,
  ).href,
  "text:sticker:v1-e55fa1fb": new URL(
    "../../assets/preset-thumbnails/text-sticker-v1-e55fa1fb.png",
    import.meta.url,
  ).href,
  "text:strawberry:v1-14ab47f3": new URL(
    "../../assets/preset-thumbnails/text-strawberry-v1-14ab47f3.png",
    import.meta.url,
  ).href,
  "text:subheading:v1-e9e22973": new URL(
    "../../assets/preset-thumbnails/text-subheading-v1-e9e22973.png",
    import.meta.url,
  ).href,
  "text:sunset:v1-de1e2ea4": new URL(
    "../../assets/preset-thumbnails/text-sunset-v1-de1e2ea4.png",
    import.meta.url,
  ).href,
  "text:team:v1-b20313be": new URL(
    "../../assets/preset-thumbnails/text-team-v1-b20313be.png",
    import.meta.url,
  ).href,
  "text:text-box:v1-eda89632": new URL(
    "../../assets/preset-thumbnails/text-text-box-v1-eda89632.png",
    import.meta.url,
  ).href,
  "text:thanks-plus:v1-bd506583": new URL(
    "../../assets/preset-thumbnails/text-thanks-plus-v1-bd506583.png",
    import.meta.url,
  ).href,
  "text:title-tag:v1-ff472b84": new URL(
    "../../assets/preset-thumbnails/text-title-tag-v1-ff472b84.png",
    import.meta.url,
  ).href,
  "text:title:v1-ca4a2f6c": new URL(
    "../../assets/preset-thumbnails/text-title-v1-ca4a2f6c.png",
    import.meta.url,
  ).href,
};
