import type { TextPreset } from "../config.types";
import { combo } from "./text-presets-combo-factory";
import { onPhotoShadow } from "./text-presets-combo-shadow";

/** Campaign lockups for launches, events, offers, and social proof. */
export const campaignCombos: TextPreset[] = [
  combo({
    id: "new-arrival",
    label: "New Arrival",
    sample: "JUST IN\nNEW ARRIVAL\nSHOP THE DROP",
    width: 0.68,
    lines: [
      {
        text: "Just in",
        scale: 0.9,
        fontWeight: "bold",
        fill: "#fb7185",
        letterSpacing: 6,
        textTransform: "uppercase",
        ...onPhotoShadow,
      },
      {
        text: "New Arrival",
        scale: 2.8,
        fontWeight: "bold",
        fill: "#ffffff",
        gap: 0.2,
        ...onPhotoShadow,
      },
      {
        text: "Shop the drop",
        scale: 0.9,
        fontWeight: "bold",
        fill: "#ffffff",
        textTransform: "uppercase",
        gap: 0.4,
        backgroundBox: {
          color: "#e11d48",
          padding: { top: 10, right: 24, bottom: 10, left: 24 },
          cornerRadius: 999,
        },
      },
    ],
  }),
  combo({
    id: "rsvp-card",
    label: "RSVP Card",
    sample: "YOU'RE INVITED\nDINNER & DANCING\nSATURDAY · 7 PM",
    width: 0.58,
    shapes: [
      {
        kind: "shape",
        layout: { x: 0.18, y: 0.3, width: 0.64, height: 0.4, rotation: -2 },
        shape: { kind: "rect", cornerRadius: 32 },
        fill: { kind: "color", color: "#fdf4ff" },
        stroke: { color: "#86198f", width: 4 },
      },
    ],
    lines: [
      {
        text: "You're invited",
        scale: 0.8,
        fontWeight: "bold",
        fill: "#a21caf",
        letterSpacing: 5,
        textTransform: "uppercase",
      },
      {
        text: "Dinner & Dancing",
        scale: 2.5,
        fontFamily: "Georgia",
        fontStyle: "italic",
        fontWeight: "bold",
        fill: "#581c87",
        gap: 0.28,
      },
      { text: "Saturday · 7 pm", scale: 0.85, fontWeight: "bold", fill: "#86198f", gap: 0.4 },
    ],
  }),
  combo({
    id: "social-proof",
    label: "Social Proof",
    sample: "★★★★★\nLOVED BY 10,000+\nCREATORS",
    width: 0.62,
    lines: [
      { text: "★★★★★", scale: 1.5, fontWeight: "bold", fill: "#fbbf24", letterSpacing: 4 },
      {
        text: "Loved by\n10,000+",
        scale: 2.35,
        fontWeight: "bold",
        fill: "#ffffff",
        lineHeight: 1.05,
        widthMode: "fixed",
        gap: 0.3,
        ...onPhotoShadow,
      },
      {
        text: "Creators worldwide",
        scale: 0.85,
        fontWeight: "bold",
        fill: "#dbeafe",
        letterSpacing: 3,
        textTransform: "uppercase",
        gap: 0.35,
        ...onPhotoShadow,
      },
    ],
  }),
  combo({
    id: "countdown",
    label: "Countdown",
    sample: "LAUNCHING IN\n03 : 12 : 45\nDAYS  HRS  MIN",
    width: 0.7,
    lines: [
      {
        text: "Launching in",
        scale: 0.9,
        fontWeight: "bold",
        fill: "#67e8f9",
        letterSpacing: 6,
        textTransform: "uppercase",
        ...onPhotoShadow,
      },
      {
        text: "03 : 12 : 45",
        scale: 2.65,
        fontWeight: "bold",
        fill: "#ffffff",
        letterSpacing: 3,
        gap: 0.3,
        ...onPhotoShadow,
      },
      {
        text: "Days     Hrs     Min",
        scale: 0.72,
        fill: "#cffafe",
        letterSpacing: 3,
        textTransform: "uppercase",
        gap: 0.25,
        ...onPhotoShadow,
      },
    ],
  }),
  combo({
    id: "shipping-banner",
    label: "Shipping Banner",
    sample: "FREE\nSHIPPING\nON ORDERS OVER $50",
    width: 0.7,
    rotation: -2,
    lines: [
      {
        text: "Free\nshipping",
        scale: 2.5,
        fontWeight: "bold",
        fill: "#052e16",
        letterSpacing: 2,
        textTransform: "uppercase",
        lineHeight: 1.05,
        widthMode: "fixed",
        backgroundBox: {
          color: "#86efac",
          padding: { top: 18, right: 34, bottom: 18, left: 34 },
          cornerRadius: 12,
          shadow: { color: "#052e16", offsetX: 10, offsetY: 10, blur: 0 },
        },
      },
      {
        text: "On orders over $50",
        scale: 0.9,
        fontWeight: "bold",
        fill: "#ffffff",
        letterSpacing: 3,
        textTransform: "uppercase",
        gap: 0.45,
        ...onPhotoShadow,
      },
    ],
  }),
];
