import type { TextPreset } from "../config.types";
import { combo } from "./text-presets-combo-factory";
import { onPhotoShadow } from "./text-presets-combo-shadow";

/** Promo / card-style "Text Combinations": badges and price stacks. */
export const promoCombos: TextPreset[] = [
  combo({
    id: "sale-badge",
    label: "Sale Badge",
    sample: "SALE\n50% OFF",
    width: 0.58,
    shapes: [
      {
        kind: "shape",
        layout: { x: 0.3, y: 0.385, width: 0.4, height: 0.23, rotation: -4 },
        shape: { kind: "ellipse" },
        fill: { kind: "color", color: "#dc2626" },
        stroke: { color: "#ffffff", width: 4 },
      },
    ],
    lines: [
      {
        text: "Sale",
        scale: 2.7,
        fontWeight: "bold",
        fill: "#ffffff",
        letterSpacing: 6,
        textTransform: "uppercase",
        ...onPhotoShadow,
      },
      {
        text: "50% off",
        scale: 1.2,
        fontWeight: "bold",
        fill: "#111827",
        backgroundColor: "#facc15",
        textTransform: "uppercase",
        gap: 0.2,
      },
      {
        text: "Limited time only",
        scale: 0.82,
        fontWeight: "bold",
        fill: "#ffffff",
        gap: 0.2,
        ...onPhotoShadow,
      },
    ],
  }),
  combo({
    id: "postcard",
    label: "Greetings",
    sample: "GREETINGS FROM\nPARIS",
    width: 0.72,
    shapes: [
      {
        kind: "shape",
        layout: { x: 0.12, y: 0.34, width: 0.76, height: 0.32, rotation: -2 },
        shape: { kind: "rect" },
        fill: { kind: "color", color: "#fff7ed" },
        stroke: { color: "#9a3412", width: 15 },
      },
    ],
    lines: [
      {
        text: "Greetings from",
        scale: 1.2,
        fontFamily: "Georgia",
        fontStyle: "italic",
        fill: "#9a3412",
      },
      {
        text: "Paris",
        scale: 3.4,
        fontWeight: "bold",
        fill: "#1f2937",
        letterSpacing: 4,
        textTransform: "uppercase",
        gap: 0.2,
      },
      {
        text: "France · Est. 1889",
        scale: 1.05,
        fontFamily: "Georgia",
        fontWeight: "bold",
        fill: "#c2410c",
        gap: 0.35,
      },
    ],
  }),
  combo({
    id: "thanks-plus",
    label: "Thanks Plus",
    sample: "THANKS\nYOU +",
    width: 0.64,
    shapes: [
      {
        kind: "shape",
        layout: { x: 0.16, y: 0.33, width: 0.68, height: 0.34, rotation: 2 },
        shape: { kind: "rect" },
        fill: { kind: "color", color: "#be123c" },
        stroke: { color: "#4c0519", width: 4 },
      },
    ],
    lines: [
      {
        text: "Thanks",
        scale: 2.8,
        fontWeight: "bold",
        fill: "#ffffff",
        letterSpacing: 3,
        textTransform: "uppercase",
      },
      {
        text: "You +",
        scale: 2.8,
        fontWeight: "bold",
        fill: "#fde047",
        letterSpacing: 3,
        textTransform: "uppercase",
        gap: 0.15,
      },
    ],
  }),
  combo({
    id: "event-details",
    label: "Live Poster",
    sample: "ONE NIGHT ONLY\nNOCTURNE\nFRI 18 OCT · 9 PM",
    width: 0.76,
    lines: [
      {
        text: "One night only",
        scale: 0.9,
        fontWeight: "bold",
        fill: "#fb7185",
        letterSpacing: 5,
        textTransform: "uppercase",
        ...onPhotoShadow,
      },
      {
        text: "Nocturne",
        scale: 3.5,
        fontFamily: "Georgia",
        fontStyle: "italic",
        fontWeight: "bold",
        fill: "#ffffff",
        gap: 0.18,
        ...onPhotoShadow,
      },
      {
        text: "Fri 18 Oct · 9 pm",
        scale: 1,
        fontWeight: "bold",
        fill: "#fef3c7",
        letterSpacing: 3,
        textTransform: "uppercase",
        gap: 0.35,
        ...onPhotoShadow,
      },
    ],
  }),
  combo({
    id: "price-stack",
    label: "Edition Mark",
    sample: "LIMITED EDITION\n07\nOF 100",
    width: 0.55,
    shapes: [
      {
        kind: "shape",
        layout: { x: 0.245, y: 0.32, width: 0.54, height: 0.38, rotation: 2 },
        shape: { kind: "rect", cornerRadius: 96 },
        fill: { kind: "color", color: "#022c22" },
        opacity: 0.5,
      },
      {
        kind: "shape",
        layout: { x: 0.22, y: 0.295, width: 0.54, height: 0.38, rotation: 2 },
        shape: { kind: "rect", cornerRadius: 96 },
        fill: { kind: "color", color: "#065f46" },
        stroke: { color: "#a7f3d0", width: 3 },
      },
    ],
    lines: [
      {
        text: "Limited edition",
        scale: 0.9,
        fontWeight: "bold",
        fill: "#fef3c7",
        letterSpacing: 5,
        textTransform: "uppercase",
        ...onPhotoShadow,
      },
      {
        text: "07",
        scale: 4.2,
        fontFamily: "Georgia",
        fontWeight: "bold",
        fill: "#ffffff",
        gap: 0.12,
        ...onPhotoShadow,
      },
      {
        text: "of 100",
        scale: 1,
        fontWeight: "bold",
        fill: "#a7f3d0",
        letterSpacing: 4,
        textTransform: "uppercase",
        gap: 0.22,
        ...onPhotoShadow,
      },
    ],
  }),
];
