import type { TextPreset } from "../config.types";
import { combo } from "./text-presets-combo-factory";
import { onPhotoShadow } from "./text-presets-combo-shadow";

/** Editorial and identity lockups for covers, quotes, and brand moments. */
export const brandCombos: TextPreset[] = [
  combo({
    id: "chapter-opener",
    label: "Chapter Opener",
    sample: "CHAPTER 04\nTHE ART\nOF LESS",
    width: 0.7,
    lines: [
      {
        text: "Chapter 04",
        scale: 0.9,
        fontWeight: "bold",
        fill: "#f59e0b",
        letterSpacing: 6,
        textTransform: "uppercase",
        ...onPhotoShadow,
      },
      {
        text: "The Art\nof Less",
        scale: 2.8,
        fontFamily: "Georgia",
        fontWeight: "bold",
        fill: "#ffffff",
        lineHeight: 1.05,
        widthMode: "fixed",
        gap: 0.25,
        ...onPhotoShadow,
      },
    ],
  }),
  combo({
    id: "pull-quote",
    label: "Pull Quote",
    sample: "DESIGN IS\nHOW IT WORKS",
    width: 0.64,
    lines: [
      {
        text: "“Design is\nnot just what\nit looks like.”",
        scale: 2.1,
        fontFamily: "Georgia",
        fontStyle: "italic",
        fontWeight: "bold",
        fill: "#ffffff",
        lineHeight: 1.08,
        widthMode: "fixed",
        ...onPhotoShadow,
      },
      {
        text: "How it works",
        scale: 0.9,
        fontWeight: "bold",
        fill: "#fbbf24",
        letterSpacing: 4,
        textTransform: "uppercase",
        gap: 0.45,
        ...onPhotoShadow,
      },
    ],
  }),
  combo({
    id: "issue-cover",
    label: "Issue Cover",
    sample: "THE JOURNAL\nISSUE 08\nNEW PERSPECTIVES",
    width: 0.72,
    lines: [
      {
        text: "The Journal",
        scale: 1,
        fontWeight: "bold",
        fill: "#ffffff",
        letterSpacing: 7,
        textTransform: "uppercase",
        ...onPhotoShadow,
      },
      {
        text: "Issue 08",
        scale: 3.8,
        fontFamily: "Georgia",
        fontWeight: "bold",
        fill: "#ffffff",
        gap: 0.3,
        ...onPhotoShadow,
      },
      {
        text: "New perspectives",
        scale: 0.9,
        fill: "#bfdbfe",
        letterSpacing: 4,
        textTransform: "uppercase",
        gap: 0.4,
        ...onPhotoShadow,
      },
    ],
  }),
  combo({
    id: "photo-caption",
    label: "Photo Caption",
    sample: "MORNING\nLIGHT\nCOPENHAGEN · 06:42",
    align: "left",
    width: 0.58,
    centerY: 0.72,
    lines: [
      {
        text: "Morning\nlight",
        scale: 2.2,
        fontFamily: "Georgia",
        fontStyle: "italic",
        fontWeight: "bold",
        fill: "#ffffff",
        lineHeight: 1.05,
        widthMode: "fixed",
        ...onPhotoShadow,
      },
      {
        text: "Copenhagen · 06:42",
        scale: 0.8,
        fontWeight: "bold",
        fill: "#fef3c7",
        letterSpacing: 3,
        textTransform: "uppercase",
        gap: 0.28,
        ...onPhotoShadow,
      },
    ],
  }),
  combo({
    id: "monogram-seal",
    label: "Monogram Seal",
    sample: "A\nATELIER\nEST. 2026",
    width: 0.42,
    shapes: [
      {
        kind: "shape",
        layout: { x: 0.33, y: 0.31, width: 0.34, height: 0.38 },
        shape: { kind: "ellipse" },
        fill: { kind: "color", color: "#fef3c7" },
        stroke: { color: "#92400e", width: 5 },
      },
    ],
    lines: [
      { text: "A", scale: 3.8, fontFamily: "Georgia", fontWeight: "bold", fill: "#78350f" },
      {
        text: "Atelier",
        scale: 0.9,
        fontWeight: "bold",
        fill: "#92400e",
        letterSpacing: 4,
        textTransform: "uppercase",
        gap: 0.2,
      },
      { text: "Est. 2026", scale: 0.72, fill: "#b45309", letterSpacing: 2, gap: 0.25 },
    ],
  }),
];
