import fs from "node:fs";
import path from "node:path";
import { expect, test } from "@playwright/experimental-ct-react";
import {
  PresetThumbnailGenerator,
  type GeneratedPresetThumbnail,
} from "./preset-thumbnail-generator.component";

const mode = process.env.EDITX_THUMBNAIL_MODE;
const packageRoot = path.resolve(__dirname, "..");
const assetDirectory = path.join(packageRoot, "src/assets/preset-thumbnails");
const manifestPath = path.join(
  packageRoot,
  "src/config/presets/preset-thumbnail-manifest.generated.ts",
);

test.skip(!mode, "Run through pnpm generate:thumbnails or pnpm check:thumbnails");
test.setTimeout(240_000);

test("generates canonical built-in preset thumbnails", async ({ mount, page }) => {
  const component = await mount(<PresetThumbnailGenerator />);
  await expect(component).toHaveAttribute("data-status", /done|failed/, { timeout: 220_000 });
  const error = await page.evaluate(() => window.__presetThumbnailGenerationError);
  expect(error).toBeUndefined();
  const results = await page.evaluate(() => window.__generatedPresetThumbnails);
  expect(results?.length).toBeGreaterThan(0);
  const output = normalizeResults(results ?? []);

  if (mode === "write") writeGeneratedOutput(output);
  else if (mode === "check") expectGeneratedOutput(output);
  else throw new Error(`Unknown EDITX_THUMBNAIL_MODE: ${mode}`);
});

function normalizeResults(results: GeneratedPresetThumbnail[]): GeneratedPresetThumbnail[] {
  const byKey = new Map<string, GeneratedPresetThumbnail>();
  for (const result of results) {
    const previous = byKey.get(result.key);
    if (previous && previous.dataUrl !== result.dataUrl) {
      throw new Error(`Conflicting built-in thumbnail key: ${result.key}`);
    }
    byKey.set(result.key, result);
  }
  return [...byKey.values()].sort((left, right) => left.key.localeCompare(right.key));
}

function writeGeneratedOutput(results: GeneratedPresetThumbnail[]): void {
  fs.mkdirSync(assetDirectory, { recursive: true });
  for (const filename of listPngs()) fs.rmSync(path.join(assetDirectory, filename));
  for (const result of results) {
    fs.writeFileSync(path.join(assetDirectory, result.filename), decodeDataUrl(result.dataUrl));
  }
  fs.writeFileSync(manifestPath, createManifest(results));
}

function expectGeneratedOutput(results: GeneratedPresetThumbnail[]): void {
  expect(listPngs()).toEqual(results.map((result) => result.filename).sort());
  for (const result of results) {
    expect(fs.readFileSync(path.join(assetDirectory, result.filename))).toEqual(
      decodeDataUrl(result.dataUrl),
    );
  }
  expect(fs.readFileSync(manifestPath, "utf8")).toBe(createManifest(results));
}

function createManifest(results: GeneratedPresetThumbnail[]): string {
  const entries = results.flatMap(({ key, filename }) => [
    `  ${JSON.stringify(key)}: new URL(`,
    `    ${JSON.stringify(`../../assets/preset-thumbnails/${filename}`)},`,
    "    import.meta.url,",
    "  ).href,",
  ]);
  return [
    "// Generated by pnpm generate:thumbnails. Do not edit manually.",
    "export const BUILT_IN_PRESET_THUMBNAILS: Readonly<Record<string, string>> = {",
    ...entries,
    "};",
    "",
  ].join("\n");
}

function listPngs(): string[] {
  if (!fs.existsSync(assetDirectory)) return [];
  return fs.readdirSync(assetDirectory).filter((filename) => filename.endsWith(".png")).sort();
}

function decodeDataUrl(dataUrl: string): Buffer {
  return Buffer.from(dataUrl.slice(dataUrl.indexOf(",") + 1), "base64");
}