// Regenerates the AUTO sections of docs-private/DASHBOARD.md and the
// local-only docs-private/dashboard.html. Run with: pnpm dashboard
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { collectMetrics, readFeatures, readFeatureTree, readFocus } from "./dashboard-lib.mjs";
import { renderHtml, renderMarkdown } from "./dashboard-render.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DOCS = join(ROOT, "docs-private");
const FEATURES = join(DOCS, "features");
const MD_PATH = join(DOCS, "DASHBOARD.md");
const HTML_PATH = join(DOCS, "dashboard.html");
const FEATURE_MAP_PATH = join(DOCS, "FEATURE_MAP.md");

const START = "<!-- AUTO:start (generated by scripts/dashboard.mjs — do not edit) -->";
const END = "<!-- AUTO:end -->";

function spliceAuto(markdown, block) {
  const generated = `${START}\n\n${block}\n\n${END}`;
  if (!existsSync(MD_PATH)) return null;
  const current = readFileSync(MD_PATH, "utf8");
  const s = current.indexOf(START);
  const e = current.indexOf(END);
  if (s === -1 || e === -1 || e < s) {
    return `${current.trimEnd()}\n\n${generated}\n`;
  }
  return current.slice(0, s) + generated + current.slice(e + END.length);
}

function main() {
  const now = new Date();
  const features = readFeatures(FEATURES);
  const metrics = collectMetrics(ROOT);
  const featureMap = existsSync(FEATURE_MAP_PATH) ? readFileSync(FEATURE_MAP_PATH, "utf8") : "";
  const tree = readFeatureTree(DOCS);
  const focus = readFocus(MD_PATH);

  const md = spliceAuto(undefined, renderMarkdown(features, metrics, now));
  if (md === null) {
    console.warn(`! ${MD_PATH} not found — skipping markdown (create it first).`);
  } else {
    writeFileSync(MD_PATH, md);
    console.log(`✓ Updated ${MD_PATH}`);
  }

  writeFileSync(HTML_PATH, renderHtml(features, metrics, now, featureMap, tree, focus));
  console.log(`✓ Wrote ${HTML_PATH}`);
  console.log(
    `  ${features.length} features · ${metrics.recipeDocs} recipes · ${metrics.engineTests + metrics.ieTests} test files · branch ${metrics.branch}`,
  );
}

main();
